name: deploy

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: vekt0r-github/randomMusicPlayer@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
